# Generated by Django 5.1.6 on 2026-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='room_no',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
